---
image: circleci/ruby:3.0.3-node-browsers

variables:
  CACHE_FALLBACK_KEY: "$CI_COMMIT_REF_SLUG"

before_script:
  - bundle config mirror.https://rubygems.org https://gems.ruby-china.com
  - bundle config set path 'vendor'  # Install dependencies into ./vendor/ruby

stages:
  - deploy

deploy_production:
  cache:
    - key:
        files:
          - Gemfile.lock
      paths:
        - vendor/ruby
  stage: deploy
  script:
    - bundle install -j $(nproc)
    - mkdir ~/.ssh
    - mv "$SSH_ID_RSA" ~/.ssh/id_rsa
    - mv "$SSH_CONFIG_FILE" ~/.ssh/config
    - bundle exec cap production deploy
  environment:
    name: production
    url: https://bbs.thape.com.cn
