---
image: "ruby:3.3"

variables:
  RAILS_ENV: test
  CACHE_FALLBACK_KEY: "$CI_COMMIT_REF_SLUG"

before_script:
  - gem install bundler --no-document
  - bundle config set path 'vendor'  # Install dependencies into ./vendor/ruby
  - bundle install --jobs $(nproc)

stages:
  - deploy

deploy_production:
  cache:
    - key:
        files:
          - Gemfile.lock
      paths:
        - vendor/ruby
  stage: deploy
  script:
    - mkdir ~/.ssh
    - mv "$SSH_ID_RSA" ~/.ssh/id_rsa
    - mv "$SSH_CONFIG_FILE" ~/.ssh/config
    - bundle exec cap production deploy
  environment:
    name: production
    url: https://bbs.thape.com.cn
