---
default:
  source_path: app/javascript
  source_entry_path: "/"
  nested_entries: false
  public_root_path: public
  public_output_path: packs
  cache_path: tmp/shakapacker
  shakapacker_compile_output: true
  additional_paths: &1
  - lib/assets/javascripts
  cache_manifest: false
  ensure_consistent_versioning: false
  swc: true

development:
  source_path: app/javascript
  source_entry_path: "/"
  nested_entries: false
  public_root_path: public
  public_output_path: packs
  cache_path: tmp/shakapacker
  shakapacker_compile_output: true
  additional_paths: *1
  cache_manifest: false
  ensure_consistent_versioning: false
  compile: true
  dev_server:
    server: http
    host: localhost
    port: 3035
    hmr: false
    inline_css: true
    client:
      overlay: true
    compress: true
    allowed_hosts: all
    pretty: true
    headers:
      Access-Control-Allow-Origin: "*"
    static:
      watch:
        ignored: "**/node_modules/**"
  swc: true
test:
  source_path: app/javascript
  source_entry_path: "/"
  nested_entries: false
  public_root_path: public
  public_output_path: packs-test
  cache_path: tmp/shakapacker
  shakapacker_compile_output: true
  additional_paths: *1
  cache_manifest: false
  ensure_consistent_versioning: false
  compile: true
  swc: true
production:
  source_path: app/javascript
  source_entry_path: "/"
  nested_entries: false
  public_root_path: public
  public_output_path: packs
  cache_path: tmp/shakapacker
  shakapacker_compile_output: true
  additional_paths: *1
  cache_manifest: true
  ensure_consistent_versioning: false
  compile: false
  swc: true
